---
title: "R Notebook"
output: html_notebook
---

# Libraries
```{r warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(Seurat)
library(ggplot2)
library(bspec)
library(sctransform)
library(cowplot)
library(gridExtra)
library(dplyr)
library(patchwork)
library(sctransform)
library(glmGamPoi)
library(SeuratDisk)
```

# Import Data
```{r}
# ------- use previously created Seurat object -------
m1c <- readRDS(file = "data/allen_m1c_2019_ssv4.rds")
```

```{r}
m1c[["percent.mt"]] <- PercentageFeatureSet(m1c, pattern = "^MT-")
m1c <- subset(m1c, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

m1c <- SCTransform(m1c, method = "glmGamPoi", vars.to.regress = "percent.mt", verbose = FALSE)
m1c <- RunPCA(m1c, features = VariableFeatures(object = m1c))
```
# Find SNN
```{r}
n = ncol(m1c)
dim(m1c)

type = c("_", "_trimmed_", "_negedges_", "_trimmed_negedges_")
id_type = 2
dim = 15
k = 5
coff = 0 #1/15
ord = 5

m1c <- FindNeighbors(m1c, reduction = "pca", dims = 1:dim, k.param=k, compute.SNN=TRUE) #prune.SNN=coff

m1c_snn_temp <- m1c@graphs[["SCT_snn"]]

dim(m1c_snn_temp)
m1c_snn <- m1c_snn_temp - diag(n)

# ------- limitation of nodes degrees -------
for (i in 1:n){
  to_delete <- order(m1c_snn[,i], decreasing = TRUE)[seq(ord+1,n,1)]
  m1c_snn[,i][to_delete] <- integer(n-ord)
  m1c_snn[i,][to_delete] <- integer(n-ord)
}
```

# Plot and save graphs 
```{r setup}
library(reticulate)
virtualenv_create("scrna_proj")
# py_install(c("networkx","matplotlib"), envname = "scrna_proj")
use_virtualenv("scrna_proj")
```

```{python}
import numpy as np
import networkx as nx
from matplotlib import pyplot as plt

id_type, type = int(r.id_type)-1, r.type
n = int(r.n)
k = int(r.k)
ord = int(r.ord)
dim = int(r.dim)

file_name = ''.join(["./m1c_graphs/", str(n), "_graph_snn", "_k", str(k), "_dim", str(dim), type[id_type], str(ord), ".gexf"])

G = nx.from_numpy_matrix(r.m1c_snn)
nx.write_gexf(G, file_name)

G = nx.read_gexf(file_name)
pos = nx.spring_layout(G)
plt.cla()
nx.draw_networkx_nodes(G, pos, node_size=10, nodelist=G.nodes)
nx.draw_networkx_edges(G, pos, edgelist=G.edges, style='solid', alpha=0.5, width=1)

file_name = ''.join(["./m1c_graphs/", str(n), "_graph_snn", "_k", str(k), "_dim", str(dim), type[id_type], str(ord), ".png"])
plt.savefig(file_name, bbox_inches='tight')
```

