---
title: "R Notebook"
output: html_notebook
---
takes QA clustered graph:   QA_clusters
takes Seurat object:        selected_a              (from "Kidney_data" notebook, original graph)
takes Seurat object:        selected_a_2            (from "Kidney_data" notebook, original graph)
# Libraries
```{r warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(Seurat)
library(ggplot2)
library(bspec)
library(sctransform)
library(cowplot)
library(gridExtra)
library(dplyr)
library(patchwork)
library(sctransform)
library(glmGamPoi)
```

# Compare clusters
## Import QA clusters
```{r setup}
library(reticulate)
virtualenv_create("scrna_proj")
# py_install(c("networkx","matplotlib"), envname = "scrna_proj")
use_virtualenv("scrna_proj")
```

```{python}
import networkx as nx
QA_output_name = "1000_cqm_graph_snn_k10_dim30_g0005_trimmed_15enh.gexf"
QA_output_name = "1000_nodes/single_enh/sample_number8.gexf"
QA_output_name = "1000_nodes/double_enh/sample_number2.gexf"
QA_output_name = "1000_nodes/1000_cqm_graph_snn_k10_dim30_g0005_trimmed_15_enh3.gexf"
QA_clusters = nx.read_gexf(''.join(["../../dataIn/kidney/", QA_output_name]))

# ------- CHOSE THE CORRECT OPTION BASED ON THE EXPORTED FORMAT -------
colors = [y[sorted(y.keys())[-1]] for x,y in sorted(QA_clusters.nodes(data=True))]
colors = [y[sorted(y.keys())[-1]] for x,y in QA_clusters.nodes(data=True)]
len(colors)
```

## Merge Clusters MetaData
```{r}
colors = py$colors
colors = unlist(colors)
selected_a <- AddMetaData(selected_a, metadata=colors, col.name="QA")
DimPlot(selected_a, reduction = "pca", group.by="QA")
```

```{r}
colors = py$colors
colors = unlist(colors)
selected_a_2<- AddMetaData(selected_a_2, metadata=colors, col.name="QA")
DimPlot(selected_a_2, reduction = "pca", group.by="QA")
```

```{r}
png(file="../../output/selected_a_seurat.png")
DimPlot(selected_a, reduction = "umap", group.by="seurat_clusters") # + NoLegend()
dev.off()

png(file="../../output/selected_a_QA.png")
DimPlot(selected_a, reduction = "umap", group.by="QA") # + NoLegend()
dev.off()

png(file="../../output/selected_a_celltypes.png")
DimPlot(selected_a, reduction = "umap", group.by="celltype") # + NoLegend()
dev.off()

par(mfrow = c(1, 2))
DimPlot(selected_a, reduction = "umap", group.by="QA") # + NoLegend()
DimPlot(selected_a, reduction = "umap", group.by="seurat_clusters") # + NoLegend()
DimPlot(selected_a, reduction = "umap", group.by="celltype") # + NoLegend()
```

```{r}
png(file="../../output/selected_a_2_seurat.png")
DimPlot(selected_a_2, reduction = "umap", group.by="seurat_clusters") # + NoLegend()
dev.off()

png(file="../../output/selected_a_2_QA.png")
DimPlot(selected_a_2, reduction = "umap", group.by="QA") # + NoLegend()
dev.off()

png(file="../../output/selected_a_2_celltypes.png")
DimPlot(selected_a_2, reduction = "umap", group.by="celltype") # + NoLegend()
dev.off()

par(mfrow = c(1, 2))
DimPlot(selected_a_2, reduction = "umap", group.by="QA") # + NoLegend()
DimPlot(selected_a_2, reduction = "umap", group.by="seurat_clusters") # + NoLegend()
DimPlot(selected_a_2, reduction = "umap", group.by="celltype") # + NoLegend()
```
