---
title: "R Notebook"
output: html_notebook
---

# Libraries
```{r warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(Seurat)
library(ggplot2)
library(bspec)
library(sctransform)
library(cowplot)
library(gridExtra)
library(dplyr)
library(patchwork)
library(sctransform)
library(glmGamPoi)
library(philentropy)
```

# Benchmarking (files' prefix: "")
takes Seurat object:    pbmc3k_QA (from "Prepare_data_for_QA_clustering" notebook)
## Within Cluster Average Distance
```{r}
# ------- Average Distance QA Clusters -------
N <- length(unique(pbmc3k_QA[["QA"]][,1]))
pbmc3k_QA_cluster <- vector("list", N)

for (i in 0:(N-1)){
 pbmc3k_QA_cluster[[i+1]] <- mean(distance(pbmc3k_QA[,which(pbmc3k_QA[["QA"]] == i)]@assays$SCT@data %>% as.matrix %>% t %>% as.data.frame, method = "jaccard"))
}
```

```{r}
# ------- Average Distance Seurat Clusters -------
N <- length(unique(pbmc3k_QA[["SCT_snn_res.1"]][,1]))
pbmc3k_Classic_cluster <- vector("list", N)

for (i in 0:(N-1)){
 pbmc3k_Classic_cluster[[i+1]] <- mean(distance(pbmc3k_QA[,which(pbmc3k_QA[["SCT_snn_res.1"]] == i)]@assays$SCT@data %>% as.matrix %>% t %>% as.data.frame, method = "jaccard"))
}
```

```{r}
# ------- do kmeans clustering -------
km.out <- kmeans(pbmc3k_QA@assays$SCT@data %>% as.matrix %>% t %>% as.data.frame, centers=9, nstart=5)
pbmc3k_QA <- AddMetaData(pbmc3k_QA, metadata=km.out$cluster, col.name="kmeans")

png(file="./output/clusters_kmeans.png")
DimPlot(pbmc3k_QA, reduction = "umap", group.by="kmeans") # + NoLegend()
dev.off()

DimPlot(pbmc3k_QA, reduction = "umap", group.by="kmeans") # + NoLegend()
```

```{r}
# ------- Average Distance Kmeans Clusters -------
N <- length(unique(pbmc3k_QA[["kmeans"]][,1]))
pbmc3k_kmeans_cluster <- vector("list", N)

for (i in 1:N){
 pbmc3k_kmeans_cluster[[i]] <- mean(distance(pbmc3k_QA[,which(pbmc3k_QA[["kmeans"]] == i)]@assays$SCT@data %>% as.matrix %>% t %>% as.data.frame, method = "jaccard"))
}
```

```{r}
matrix(c(sort(unlist(pbmc3k_kmeans_cluster), decreasing = FALSE), sort(unlist(pbmc3k_QA_cluster), decreasing = FALSE), sort(unlist(pbmc3k_Classic_cluster), decreasing = FALSE)), ncol = 3)
```

## Average silhouette width (the higher the better)
```{r}
library(cluster)
silhouette_results_kmeans <- silhouette(pbmc3k_QA[["kmeans"]][,1], distance(pbmc3k_QA@assays$SCT@data %>% as.matrix %>% t %>% as.data.frame, method = "jaccard"))
silhouette_sum_kmeans <- sum(silhouette_results_kmeans[,"sil_width"])

silhouette_results_QA <- silhouette(pbmc3k_QA[["QA"]][,1], distance(pbmc3k_QA@assays$SCT@data %>% as.matrix %>% t %>% as.data.frame, method = "jaccard"))
silhouette_sum_QA <- sum(silhouette_results_QA[,"sil_width"])

silhouette_results_seurat <- silhouette(as.numeric(as.vector(pbmc3k_QA[["seurat_clusters"]][,1])), distance(pbmc3k_QA@assays$SCT@data %>% as.matrix %>% t %>% as.data.frame, method = "jaccard"))
silhouette_sum_seurat <- sum(silhouette_results_seurat[,"sil_width"])

c(silhouette_sum_kmeans, silhouette_sum_QA, silhouette_sum_seurat)
```

## fpc library statistics
```{r}
library("fpc")
QA_stats <- cluster.stats(distance(pbmc3k_QA@assays$SCT@data %>% as.matrix %>% t %>% as.data.frame, method = "jaccard"), pbmc3k_QA[["QA"]][,1])
```
```{r}
Seurat_stats <- cluster.stats(distance(pbmc3k_QA@assays$SCT@data %>% as.matrix %>% t %>% as.data.frame, method = "jaccard"), pbmc3k_?[["QA"]][,1])
```
```{r}
Kmeans_stats <- cluster.stats(distance(pbmc3k_QA@assays$SCT@data %>% as.matrix %>% t %>% as.data.frame, method = "jaccard"), pbmc3k_?[["QA"]][,1])
```
```{r}
# add here heretical tree clustering (e.g. clustree())
```




